#' GetDIRWithNoReplicate
#'
#' @description
#' This function reads interaction counts and performs differential analysis between two conditions.
#' This function is specifically for experiments without biological replicate.
#' Hence the result has no statistical significance.
#' Please treat the log2 fold change, p value, or FDR as descriptive values.
#' 
#' @author Tsunghan Hsieh
#'
#' @param chr a character string specifying the interaction regions from which chromosome 
#' @param treat a character string specifying the name and path of the treatment file (.csv)
#' @param ctrl a character string specifying the name and path of the control file (.csv)
#' @param start_position_index a character string specifying the name and path of the start position index (.txt)
#' The above three files are generated by ./Python/subset_hic_data.py
#' @param output A character string specifying the name and path of output file
#' the default path is as same as the treatment file
#' the default output file name is the treatment file name prefixed with "DIR_"
#' @return a dataframe of the output data
#'
#' @export
#'
#' @importFrom here here
#' @importFrom edger
#' @importFrom assertthat assert_that
#' @importFrom dplyr select mutate left_join
#' @importFrom tidyr separate
#'
#' @examples
#' \dontrun{
#' df <- GetDIRWithNoReplicate(
#' chr = "chr2",
#' treat = here::here("./Results/processing/44112_A_bg_43615_mc6contact_map_extracted.csv"),
#' ctrl = here::here("./Results/processing/44111_A_ctrl_43614_mc5contact_map_extracted.csv"),
#' start_position_index = here::here("./Results/processing/start_position_index.txt"),
#' output = NULL
#' )
#' }

## Get differentiation regions from microC experiments

## TODO
## Run python ./Python/subset_hic_data.py to generate the dataframe

GetDIRWithNoReplicate <- function(chr, treat, ctrl, start_position_index, output) {
  # check input ----------------------------------------------------------------
  
  assertthat::assert_that(is.character(chr), 
                          msg = "The given argument is not a string.\n")
  
  assertthat::assert_that(is.character(treat), 
                          msg = "The given argument is not a string.\n")
  
  assertthat::assert_that(grepl("\\.csv$", treat), 
                          msg = "The given file to the input file is not a .csv file.\n")
  
  assertthat::assert_that(file.exists(here::here(treat)), 
                          msg = "The given file path to the input file does not exist.\n")
  
  assertthat::assert_that(is.character(ctrl), 
                          msg = "The given argument is not a string.\n")
  
  assertthat::assert_that(grepl("\\.csv$", ctrl), 
                          msg = "The given file to the experiment file is not a .csv file.\n")
  
  assertthat::assert_that(file.exists(here::here(ctrl)), 
                          msg = "The given file path to the expertiment file does not exist.\n")
  
  assertthat::assert_that(is.character(start_position_index), 
                          msg = "The given argument is not a string.\n")
  
  assertthat::assert_that(grepl("\\.txt$", start_position_index), 
                          msg = "The given file to the experiment file is not a .csv file.\n")
  
  assertthat::assert_that(file.exists(here::here(start_position_index)), 
                          msg = "The given file path to the expertiment file does not exist.\n")
  
  # check output ---------------------------------------------------------------
  
  if (is.null(output)) {
    # Use sub() to extract the desired part
    outputfname <- sub(".*/([^.]+)\\.csv", "\\1", treat)
    outputfname <- paste0("DIR_", outputfname, ".csv")
    outputdir <- dirname(treat)
    output <- here::here(outputdir, outputfname)
    remove(outputfname, outputdir)
  } else {
    assertthat::assert_that(is.character(output), 
                            msg = "The given argument is not a string.\n")
    
    assertthat::assert_that(grepl("\\.csv$", output), 
                            msg = "The given file to the output file is not a .csv file.\n")
    
    assertthat::assert_that(file.exists(here::here(dirname(output))), 
                            msg = "The given file path to the expertiment file does not exist.\n")
  }
  
  # read start position index  -------------------------------------------------
  start_position_index <- readLines(start_position_index, n = -1)
  
  treat_df <- .generateInteractionMatrixCount(treat, start_position_index)
  ctrl_df <- .generateInteractionMatrixCount(ctrl, start_position_index)
  
  # combine the dataframe ------------------------------------------------------
  combine_df <- treat_df |>
    dplyr::left_join(ctrl_df, by = "interaction_index")
  
  rownames(combine_df) <- combine_df$interaction_index
  combine_df <- combine_df[,2:ncol(combine_df)]
  colnames(combine_df) <- c("treat", "ctrl")
  
  # Perform differential analysis ----------------------------------------------
  ## The biological covariance is set 0.4 according to the empirical data ------
  ## See section 2.12 
  ## https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf
  
  bcv <- 0.4
  dir_df <- DGEList(counts=combine_df, group=1:2)
  
  et <- exactTest(dir_df, dispersion=bcv^2)
  et <- as.data.frame(et)
  et$interaction_index <- rownames(et)
  
  # Generate the result dataframe  ---------------------------------------------
  result <- data.frame(chr = chr, interaction_index = treat_df$interaction_index)
  
  result <- result |>
    tidyr::separate(interaction_index, c("start", "end"), remove = FALSE) |>
    dplyr::mutate(start = as.numeric(start),
                  end = as.numeric(end)) |>
    dplyr::left_join(et, by = "interaction_index") |>
    dplyr::select(-c(interaction_index))
  remove(et)
  
  write.csv(result, output)
  message("Done! The file is written into: ", output)
  return(result)
}


#' .generateInteractionMatrixCount
#' @description
#' Get the interaction count dataframe
#' @param file a character specifying the input file
#' The inputfile is a interaction matrix
#' @param start_position_index a dataframe containing the starting position of the each interaction
#  The above two files are generated by ./Python/subset_hic_data.py
#' @return a dataframe containing the interaction index and count
#'  
.generateInteractionMatrixCount <- function(file, start_position_index) {
  df <- read.csv(file, header = FALSE)
  df <- df[2:nrow(df),]
  df <- df[,2:ncol(df)]
  df_final <- data.frame(matrix(nrow=length(start_position_index)^2, ncol=2))
  colnames(df_final) <- c("interaction_index", "count")
  interaction_index_list <- list()
  for (i in  1:length(start_position_index)) {
    for (j in 1:length(start_position_index)) {
      interaction_index_list[[paste0(start_position_index[i], "-", start_position_index[j])]] <- df[i,j]
    }
  }
  remove(i,j)
  for (i in 1:length(interaction_index_list)) {
    df_final[i,]$interaction_index <- names(interaction_index_list[i])
    df_final[i,]$count <- as.numeric(interaction_index_list[i][[1]])
  }
  remove(i)
  return(df_final)
}