#' GetDIRWithNoReplicate
#'
#' @description
#' This function reads interaction counts and performs differential analysis between two conditions.
#' This function is specifically for experiments without biological replicate.
#' Hence the result has no statistical significance.
#' Please treat the log2 fold change, p value, or FDR as descriptive values.
#' 
#' @author Tsunghan Hsieh
#'
#' @param chr a character string specifying the interaction regions from which chromosome 
#' @param treat a character string specifying the name and path of the treatment file (.csv)
#' @param ctrl a character string specifying the name and path of the control file (.csv)
#' @param bcv a number specifying the hypothetical biological covaraiance, default is 0.4
#' See section 2.12 
#' https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf
#' @param start_position_index a character string specifying the name and path of the start position index (.txt)
#' The above three files are generated by ./Python/subset_hic_data.py
#' @param output A character string specifying the name and path of output file
#' the default path is as same as the treatment file
#' the default output file name is the treatment file name prefixed with "DIR_"
#' @return a dataframe of the output data
#'
#' @export
#'
#' @importFrom here here
#' @importFrom edger
#' @importFrom assertthat assert_that
#' @importFrom dplyr select mutate left_join
#' @importFrom tidyr separate
#'
#' @examples
#' \dontrun{
#' df <- GetDIRWithNoReplicate(
#' chr = "chr2",
#' treat = here::here("./Results/processing/44112_A_bg_43615_mc6contact_map_extracted.csv"),
#' ctrl = here::here("./Results/processing/44111_A_ctrl_43614_mc5contact_map_extracted.csv"),
#' bcv = 0.4,
#' start_position_index = here::here("./Results/processing/start_position_index.txt"),
#' output = NULL
#' )
#' }

## Get differentiation regions from microC experiments

## TODO
## Run python ./Python/subset_hic_data.py to generate the dataframe
## Run GetInteractionPosIndex()
##

GetDIRWithNoReplicate <- function(chr, treat, ctrl, bcv, start_position_index, output) {
  # check input ----------------------------------------------------------------
  
  assertthat::assert_that(is.character(chr), 
                          msg = "The given argument is not a string.\n")
  
  assertthat::assert_that(is.character(treat), 
                          msg = "The given argument is not a string.\n")
  
  assertthat::assert_that(grepl("\\.csv$", treat), 
                          msg = "The given file to the input file is not a .csv file.\n")
  
  assertthat::assert_that(file.exists(here::here(treat)), 
                          msg = "The given file path to the input file does not exist.\n")
  
  assertthat::assert_that(is.character(ctrl), 
                          msg = "The given argument is not a string.\n")
  
  assertthat::assert_that(grepl("\\.csv$", ctrl), 
                          msg = "The given file to the experiment file is not a .csv file.\n")
  
  assertthat::assert_that(file.exists(here::here(ctrl)), 
                          msg = "The given file path to the expertiment file does not exist.\n")
  
  assertthat::assert_that(is.numeric(bcv), 
                          msg = "The given argument is not a number.\n")
  
  assertthat::assert_that(is.character(start_position_index), 
                          msg = "The given argument is not a string.\n")
  
  assertthat::assert_that(grepl("\\.txt$", start_position_index), 
                          msg = "The given file to the experiment file is not a .csv file.\n")
  
  assertthat::assert_that(file.exists(here::here(start_position_index)), 
                          msg = "The given file path to the expertiment file does not exist.\n")
  
  # check output ---------------------------------------------------------------
  
  if (is.null(output)) {
    # Use sub() to extract the desired part
    outputfname <- sub(".*/([^.]+)\\.csv", "\\1", treat)
    outputfname <- paste0("DIR_", outputfname, ".csv")
    outputdir <- dirname(treat)
    output <- here::here(outputdir, outputfname)
    remove(outputfname, outputdir)
  } else {
    assertthat::assert_that(is.character(output), 
                            msg = "The given argument is not a string.\n")
    
    assertthat::assert_that(grepl("\\.csv$", output), 
                            msg = "The given file to the output file is not a .csv file.\n")
    
    assertthat::assert_that(file.exists(here::here(dirname(output))), 
                            msg = "The given file path to the expertiment file does not exist.\n")
  }
  
  # read start position index  -------------------------------------------------
  start_position_index <- readLines(start_position_index, n = -1)
  
  treat_df <- .generateInteractionMatrixCount(treat, start_position_index)
  ctrl_df <- .generateInteractionMatrixCount(ctrl, start_position_index)
  
  # combine the dataframe ------------------------------------------------------
  combine_df <- treat_df |>
    dplyr::left_join(ctrl_df, by = "index")
  
  rownames(combine_df) <- combine_df$index
  combine_df <- combine_df[,2:ncol(combine_df)]
  colnames(combine_df) <- c("treat", "ctrl")
  
  # Perform differential analysis ----------------------------------------------
  dir_df <- DGEList(counts=combine_df, group=1:2)
  
  et <- exactTest(dir_df, dispersion=bcv^2)
  et <- as.data.frame(et)
  et$index <- rownames(et)
  
  # Generate the result dataframe  ---------------------------------------------
  result <- data.frame(chr = chr, index = treat_df$index)
  
  result <- result |>
    tidyr::separate(index, c("region1", "region2"), remove = FALSE) |>
    dplyr::mutate(region1 = as.numeric(region1),
                  region2 = as.numeric(region2)) |>
    dplyr::left_join(et, by = "index") |>
    dplyr::select(-c(index))
  remove(et)
  
  write.csv(result, output)
  message("Done! The file is written into: ", output)
  return(result)
}


#' .generateInteractionMatrixCount
#' @description
#' Get the interaction count dataframe
#' @param file a character specifying the input file
#' The inputfile is a interaction matrix
#' @param start_position_index a dataframe containing the starting position of the each interaction
#  The above two files are generated by ./Python/subset_hic_data.py
#' @return a dataframe containing the interaction index and count
#'  
.generateInteractionMatrixCount <- function(file, start_position_index) {
  df <- read.csv(file, header = FALSE)
  df_final <- data.frame(matrix(nrow=0, ncol=1))
  start_position_index = data.frame(index = as.data.frame(start_position_index))
  for (i in 1:nrow(df)) {
    for (j in 1:nrow(df)) {
      df_final <- rbind(df_final, df[i,j])
    }
  }
  df_final <- cbind(start_position_index, df_final)
  colnames(df_final) <- c("index", "count")
  return(df_final)
}