## Get differentiation regions from microC experiments

## TODO
## Run ./Python/subset_hic_test.ipynb to generate the dataframe

library(DESeq2)
library(here)

# input dir --------------------------------------------------------------------
input_dir <- here::here("./Results/processing")
output_dir <- here::here("./Results/DIR")

# Sample df --------------------------------------------------------------------
## Create a sample dataframe for describing the experiment conditions

file_list <- list.files(input_dir, pattern = "\\.csv$")

sample_df <- data.frame(file = file_list) 
sample_df <- sample_df |> 
  tidyr::separate(file, c("id1", "donor", "condition", "id2"), remove = FALSE) |>
  dplyr::mutate(sample = paste0(donor, "_", condition))

# Generate the interaction count file ------------------------------------------
## Get the start position index
start_index_file <- here::here(input_dir, "start_position_index.txt")
start_position_index <- readLines(start_index_file, n = -1)

## Generate the interaction count data frame
interaction_count_list <- list()
for (i in 1:nrow(sample_df)) {
  file <- here::here(input_dir, sample_df[i,]$file)
  sample <- sample_df[i,]$sample
  interaction_count_list[[sample]] <- .generateInteractionMatrixCount(file,start_position_index)
}
remove(i, file, sample)

# Generate the count matrix for DeSeq2 -----------------------------------------
count <- as.data.frame(matrix(nrow=length(start_position_index)^2, ncol=1))
count[,1] <- interaction_count_list[[1]]$interaction_index
colnames(count) <- "interaction_index"
for (i in 1:nrow(sample_df)) {
  sample <- sample_df[i,]$sample
  df_tmp <- interaction_count_list[[sample]]
  colnames(df_tmp) <- c("interaction_index", sample)
  count <- count |>
    dplyr::left_join(df_tmp, by = "interaction_index")
}
remove(i, df_tmp)
rownames(count) <- count$interaction_index
count <- count |>
  dplyr::select(-c(interaction_index))

# Perform differential analysis ------------------------------------------------
## BG
## condition <- "bg"
## donor <- "A"
condition <- "lps"
donor <- "C"
sample_df_subset <- sample_df |>
  dplyr::filter(donor == !!donor)
count_subset <- round(count[ , grepl(donor , names(count))])
rownames(sample_df_subset) <- colnames(count_subset)
dds <- DESeqDataSetFromMatrix(countData=count_subset, 
                              colData=sample_df_subset, 
                              design=~ 1) # only one replicate, not sure if the setting is correct
dds <- DESeq(dds)
res <- results(dds)
res <- as.data.frame(res[order(res$padj),])

write.csv(res, here::here(output_dir, paste0("DIRs_", donor, "_", condition, ".csv")))

sig_num <- res  |>
  dplyr::filter(padj < 0.05) |>
  dplyr::filter(log2FoldChange>1 || log2FoldChange<-1)




#' .generateInteractionMatrixCount
#' @description
#' Get the interaction count dataframe
#' @param file a character specifying the input file
#' The inputfile is a interaction matrix generated by subset_hic_test.ipynb
#' @param start_position_index a dataframe containing the starting position of the each interaction, generated by subset_hic_test.ipynb
#' @return a dataframe containing the interaction index and count
#'  
.generateInteractionMatrixCount <- function(file, start_position_index) {
  df <- read.csv(file, header = FALSE)
  df <- df[2:nrow(df),]
  df <- df[,2:ncol(df)]
  df_final <- data.frame(matrix(nrow=length(start_position_index)^2, ncol=2))
  colnames(df_final) <- c("interaction_index", "count")
  interaction_index_list <- list()
  for (i in  1:length(start_position_index)) {
    for (j in 1:length(start_position_index)) {
      interaction_index_list[[paste0(start_position_index[i], "-", start_position_index[j])]] <- df[i,j]
    }
  }
  remove(i,j)
  for (i in 1:length(interaction_index_list)) {
    df_final[i,]$interaction_index <- names(interaction_index_list[i])
    df_final[i,]$count <- as.numeric(interaction_index_list[i][[1]])
  }
  remove(i)
  return(df_final)
}
